"""Graph 4 -- real vs shuffled correlation distributions (the noise floor).

1,770 pairwise correlations are estimated from 86 respondents. Two unrelated
questions do not correlate at 0.00: they scatter around zero with typical
spread 1/sqrt(n-3) ~ 0.109. Across 1,770 pairs, a large number land high purely
by luck. That is the noise floor -- not bad data, but irreducible sampling
scatter -- and any threshold chosen without reference to it is arbitrary.

The null is generated by re-running the entire pipeline (permute -> row-centre
-> correlate) on column-permuted responses, not by shuffling a finished
correlation matrix.
"""

from __future__ import annotations

import json

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.common.config import (
    ARTIFACTS,
    DPI,
    FIGDIR_P2,
    MARK_COLOR,
    N_NULL_REPS,
    NULL_COLOR,
    REAL_COLOR,
    REPORT_THRESHOLDS,
    SEED,
    THRESHOLD_GRID,
    ensure_dirs,
)
from src.common.matrix import (
    AnalysisMatrix,
    build_matrices,
    correlation,
    save_matrices,
    upper_triangle,
)
from src.common.nulls import cache_replicates, permutation_null

SPEC = {
    0.15: "467 / 309 (66%)",
    0.20: "258 / 118 (46%)",
    0.25: "111 / 37 (33%)",
    0.30: "49 / 9 (18%)",
}


def pipeline_fn(X_permuted: np.ndarray) -> np.ndarray:
    """The full pipeline the permutation null re-runs per replicate.

    Row-centring happens here, on already-shuffled data, because centring is
    part of the pipeline being tested -- not a preprocessing step applied once
    outside it.
    """
    centred = X_permuted - X_permuted.mean(axis=1, keepdims=True)
    return upper_triangle(np.corrcoef(centred.T))


def compute_noise_floor(am: AnalysisMatrix, n_reps: int = N_NULL_REPS, seed: int = SEED):
    """Real correlations plus n_reps permutation replicates of the same pipeline."""
    real_r = upper_triangle(correlation(am.centred))
    reps = permutation_null(
        am.encoded.to_numpy(),
        pipeline_fn,
        n_reps=n_reps,
        seed=seed,
        progress_every=50,
    )
    return real_r, np.vstack(reps)


def chance_edge_table(real_r, null_matrix, grid=THRESHOLD_GRID) -> pd.DataFrame:
    """Real vs mean-chance edge counts at every candidate threshold."""
    rows = []
    abs_real = np.abs(real_r)
    abs_null = np.abs(null_matrix)
    for t in grid:
        real_edges = int((abs_real > t).sum())
        per_rep = (abs_null > t).sum(axis=1)
        chance = float(per_rep.mean())
        rows.append(
            {
                "threshold": round(float(t), 4),
                "real_edges": real_edges,
                "chance_edges_mean": chance,
                "chance_edges_sd": float(per_rep.std(ddof=1)),
                "chance_fraction": (chance / real_edges) if real_edges else np.nan,
                "excess_over_chance": real_edges - chance,
            }
        )
    return pd.DataFrame(rows)


def report_numbers(real_r, null_matrix, table, n_respondents: int) -> dict:
    """Print the acceptance criteria before anything is plotted."""
    pooled = null_matrix.ravel()
    theory = 1 / np.sqrt(n_respondents - 3)
    print("=" * 74)
    print("GRAPH 4 ACCEPTANCE CRITERIA")
    print("=" * 74)
    print(f"  pairwise correlations        {len(real_r):>8,}    (spec 1,770)")
    print(f"  permutation replicates       {null_matrix.shape[0]:>8,}")
    print(f"  real correlation SD          {real_r.std():>8.4f}    (spec 0.136)")
    print(f"  shuffled correlation SD      {pooled.std():>8.4f}    (spec 0.108)")
    print(f"  theoretical 1/sqrt(n-3)      {theory:>8.4f}    (spec 0.109)")
    print()
    print(f"  {'threshold':>10} {'real':>8} {'chance':>8} {'chance %':>9}   spec")
    for t in REPORT_THRESHOLDS:
        row = table.loc[np.isclose(table["threshold"], t)].iloc[0]
        print(
            f"  {t:>10.2f} {int(row['real_edges']):>8} {row['chance_edges_mean']:>8.1f} "
            f"{row['chance_fraction'] * 100:>8.0f}%   {SPEC[t]}"
        )
    print("=" * 74)
    return {
        "real_sd": float(real_r.std()),
        "shuffled_sd": float(pooled.std()),
        "theoretical_sd": float(theory),
        "n_pairs": int(len(real_r)),
        "n_replicates": int(null_matrix.shape[0]),
        "n_respondents": int(n_respondents),
    }


def plot_noise_floor(real_r, null_matrix, table, path_stem) -> None:
    pooled = null_matrix.ravel()
    bins = np.linspace(-0.6, 0.6, 61)

    fig, (ax1, ax2) = plt.subplots(
        2, 1, figsize=(6.5, 6.1), gridspec_kw={"height_ratios": [1.3, 0.95]}
    )

    # --- (a) distributions on shared bin edges ----------------------------
    ax1.hist(
        pooled,
        bins=bins,
        density=True,
        color=NULL_COLOR,
        alpha=0.50,
        edgecolor="white",
        linewidth=0.4,
        label=f"Permuted null, {null_matrix.shape[0]} reps (SD = {pooled.std():.3f})",
    )
    ax1.hist(
        real_r,
        bins=bins,
        density=True,
        histtype="step",
        color=REAL_COLOR,
        linewidth=2.2,
        label=f"Observed (SD = {real_r.std():.3f})",
    )
    # Headroom so the legend does not clip the null histogram peak.
    ax1.set_ylim(top=ax1.get_ylim()[1] * 1.18)
    top = ax1.get_ylim()[1]
    for t in REPORT_THRESHOLDS:
        for s in (-1, 1):
            ax1.axvline(s * t, color=MARK_COLOR, linestyle="--", linewidth=0.9, alpha=0.65)
        # Rotated so the four labels do not collide: they sit only 0.05 apart.
        ax1.text(
            t,
            top * 0.62,
            f"$|r|$ = {t:.2f}",
            ha="right",
            va="center",
            rotation=90,
            fontsize=8.5,
            color=MARK_COLOR,
        )
    ax1.set_xlabel("Pearson correlation $r$ between item pairs")
    ax1.set_ylabel("Density")
    ax1.set_title(
        "(a) Observed item-item correlations against the permuted noise floor",
        fontsize=11,
        loc="left",
    )
    ax1.legend(fontsize=9.5, loc="upper left", framealpha=0.9)
    ax1.set_xlim(-0.6, 0.6)

    # --- (b) real vs chance edge counts -----------------------------------
    ax2.plot(
        table["threshold"], table["real_edges"], color=REAL_COLOR, linewidth=2.2, label="Observed edges"
    )
    ax2.plot(
        table["threshold"],
        table["chance_edges_mean"],
        color=NULL_COLOR,
        linewidth=2.0,
        linestyle="--",
        label="Expected by chance (permuted null)",
    )
    ax2.fill_between(
        table["threshold"],
        table["chance_edges_mean"],
        table["real_edges"],
        color=REAL_COLOR,
        alpha=0.13,
        label="Excess over chance",
    )
    for t in REPORT_THRESHOLDS:
        row = table.loc[np.isclose(table["threshold"], t)].iloc[0]
        ax2.axvline(t, color=MARK_COLOR, linestyle="--", linewidth=0.9, alpha=0.65)
        ax2.annotate(
            f"{row['chance_fraction'] * 100:.0f}%\nchance",
            xy=(t, row["chance_edges_mean"]),
            xytext=(5, -22),
            textcoords="offset points",
            fontsize=8.5,
            color=MARK_COLOR,
            linespacing=1.1,
        )
    ax2.set_xlabel("Edge threshold $|r|$")
    ax2.set_ylabel("Number of edges")
    ax2.set_title(
        "(b) Surviving edges versus edges expected from sampling scatter alone",
        fontsize=11,
        loc="left",
    )
    ax2.set_yscale("log")
    ax2.legend(fontsize=9.5, loc="lower left")
    ax2.set_xlim(0.05, 0.50)

    for ax in (ax1, ax2):
        ax.grid(alpha=0.22, linewidth=0.6)
        ax.set_axisbelow(True)
    fig.tight_layout()
    for ext in ("png", "pdf"):
        fig.savefig(f"{path_stem}.{ext}", dpi=DPI, bbox_inches="tight")
    plt.close(fig)


def main(n_reps: int = N_NULL_REPS) -> dict:
    ensure_dirs()
    am = build_matrices()
    # The spec-conformant centred matrix is a handoff artefact in its own right:
    # src/loader.py does not apply the >12-missing filter, so nothing else writes it.
    save_matrices(am)
    real_r, null_matrix = compute_noise_floor(am, n_reps=n_reps)
    table = chance_edge_table(real_r, null_matrix)
    stats = report_numbers(real_r, null_matrix, table, n_respondents=len(am.encoded))

    table.to_csv(ARTIFACTS / "chance_edges_by_threshold.csv", index=False)
    cache_replicates(
        ARTIFACTS / "null_replicates.npz",
        null_corr=null_matrix.astype(np.float32),
        real_corr=real_r.astype(np.float64),
    )
    (ARTIFACTS / "noise_floor_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")
    plot_noise_floor(real_r, null_matrix, table, FIGDIR_P2 / "graph_4_noise_floor")
    print(f"\n  wrote {FIGDIR_P2 / 'graph_4_noise_floor'}.png / .pdf")
    print("  wrote artifacts/chance_edges_by_threshold.csv, null_replicates.npz")
    print("  wrote artifacts/X_encoded.npy, X_centred.npy, items.json")
    return stats


if __name__ == "__main__":
    main()
